server:
  port: 8081
spring:
  main:
    banner-mode: off

  datasource:
#    spring.datasource.url=jdbc:h2:file:./data/testdb
    url: jdbc:postgresql://localhost:5433/bank
    username: postgres
    password: 3123Mira

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

#????????? ??? postgresql

#spring.datasource.url=jdbc:postgresql://localhost/sweater
#spring.datasource.username=postgres
#spring.datasource.password=3123Mira
#spring.jpa.generate-ddl=true